spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${databaseUrl}
    username: ${databaseUser}
    password: ${databasePwd}

  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
            revision_field_name: rev_id
            revision_type_field_name: rev_type

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer

cloud:
  aws:
    stack:
      auto: false
    credentials:
      use-default-aws-credentials-chain: true
    s3:
      bucket: springboot-guide-images
      url: https://springboot-guide-images.s3.ap-northeast-2.amazonaws.com/
    region:
      static: ap-northeast-2

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub